# Generated by Django 5.2.7 on 2025-10-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('document', models.CharField(max_length=20, verbose_name='Nº Documento')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], max_length=10, verbose_name='Sexo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('name',),
            },
        ),
    ]
